services:
  db_for_app:
   image: mongo
   container_name: main_db
   ports:
    - "27017:27017"
   environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: password
   volumes:
    - db_data_main:/data/db
   healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.adminCommand(ping)"]
    interval: 10s
    timeout: 5s
    start_period: 50s
    retries: 3
  db_gui:
   image: mongo-express
   container_name: db_gui
   ports:
    - "8081:8081"
   environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ME_CONFIG_MONGODB_SERVER: db_for_app
    ME_CONFIG_BASICAUTH_USERNAME: admin
    ME_CONFIG_BASICAUTH_PASSWORD: password
   depends_on:
    db_for_app:
     condition: service_healthy
  python-app:
   build: ./app
   ports:
    - "5000:5000"
   depends_on:
    db_for_app:
     condition: service_healthy
volumes:
  db_data_main:             